[32m2021-06-22 11:23:22[0m - dagster - [34mDEBUG[0m - apis_pipeline - d0e750ab-22e1-4c88-8aa3-4d4facd4b7ff - 817 - portals_dataframe - LOGS_CAPTURED - Started capturing logs for solid: portals_dataframe.
[32m2021-06-22 11:23:22[0m - dagster - [34mDEBUG[0m - apis_pipeline - d0e750ab-22e1-4c88-8aa3-4d4facd4b7ff - 817 - portals_dataframe - STEP_START - Started execution of step "portals_dataframe".
[32m2021-06-22 11:23:22[0m - dagster - [34mDEBUG[0m - apis_pipeline - d0e750ab-22e1-4c88-8aa3-4d4facd4b7ff - 817 - portals_dataframe - LOADED_INPUT - Loaded input "results" using input manager "io_manager", from output "result" of step "query_portals"
[32m2021-06-22 11:23:23[0m - dagster - [34mDEBUG[0m - apis_pipeline - d0e750ab-22e1-4c88-8aa3-4d4facd4b7ff - 817 - portals_dataframe - STEP_INPUT - Got input "results" of type "Any". (Type check passed).
[32m2021-06-22 11:23:23[0m - dagster - [34mERROR[0m - [31mapis_pipeline - d0e750ab-22e1-4c88-8aa3-4d4facd4b7ff - 817 - portals_dataframe - STEP_FAILURE - Execution of step "portals_dataframe" failed.

dagster.core.errors.DagsterExecutionStepExecutionError: Error occurred while executing solid "portals_dataframe"::

TypeError: 'NoneType' object is not subscriptable

Stack Trace:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/core/execution/plan/utils.py", line 42, in solid_execution_error_boundary
    yield
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/utils/__init__.py", line 382, in iterate_with_context
    next_output = next(iterator)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/core/definitions/decorators/solid.py", line 307, in _coerce_solid_compute_fn_to_iterator
    result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
  File "/mnt/d/ims/situated-views/bin/solids/apis.py", line 204, in portals_dataframe
    prefix = context.solid_config["url"]
[0m
