[32m2021-07-22 18:09:55[0m - dagster - [34mDEBUG[0m - metadata_pipeline - 81f73056-151b-40a3-aa30-1ca9bcc9a997 - 5758 - create_metadata - LOGS_CAPTURED - Started capturing logs for solid: create_metadata.
[32m2021-07-22 18:09:55[0m - dagster - [34mDEBUG[0m - metadata_pipeline - 81f73056-151b-40a3-aa30-1ca9bcc9a997 - 5758 - create_metadata - STEP_START - Started execution of step "create_metadata".
[32m2021-07-22 18:10:01[0m - dagster - [34mDEBUG[0m - metadata_pipeline - 81f73056-151b-40a3-aa30-1ca9bcc9a997 - 5758 - create_metadata - LOADED_INPUT - Loaded input "camera" using input manager "camera_root"
[32m2021-07-22 18:10:01[0m - dagster - [34mDEBUG[0m - metadata_pipeline - 81f73056-151b-40a3-aa30-1ca9bcc9a997 - 5758 - create_metadata - LOADED_INPUT - Loaded input "cumulus" using input manager "cumulus_root"
[32m2021-07-22 18:10:01[0m - dagster - [34mDEBUG[0m - metadata_pipeline - 81f73056-151b-40a3-aa30-1ca9bcc9a997 - 5758 - create_metadata - LOADED_INPUT - Loaded input "images" using input manager "images_root"
[32m2021-07-22 18:10:01[0m - dagster - [34mDEBUG[0m - metadata_pipeline - 81f73056-151b-40a3-aa30-1ca9bcc9a997 - 5758 - create_metadata - LOADED_INPUT - Loaded input "jstor" using input manager "jstor_root"
[32m2021-07-22 18:10:02[0m - dagster - [34mDEBUG[0m - metadata_pipeline - 81f73056-151b-40a3-aa30-1ca9bcc9a997 - 5758 - create_metadata - LOADED_INPUT - Loaded input "portals" using input manager "portals_root"
[32m2021-07-22 18:10:02[0m - dagster - [34mDEBUG[0m - metadata_pipeline - 81f73056-151b-40a3-aa30-1ca9bcc9a997 - 5758 - create_metadata - LOADED_INPUT - Loaded input "wikidata" using input manager "wikidata_root"
[32m2021-07-22 18:10:02[0m - dagster - [34mDEBUG[0m - metadata_pipeline - 81f73056-151b-40a3-aa30-1ca9bcc9a997 - 5758 - create_metadata - STEP_INPUT - Got input "camera" of type "Any". (Type check passed).
[32m2021-07-22 18:10:02[0m - dagster - [34mDEBUG[0m - metadata_pipeline - 81f73056-151b-40a3-aa30-1ca9bcc9a997 - 5758 - create_metadata - STEP_INPUT - Got input "cumulus" of type "Any". (Type check passed).
[32m2021-07-22 18:10:02[0m - dagster - [34mDEBUG[0m - metadata_pipeline - 81f73056-151b-40a3-aa30-1ca9bcc9a997 - 5758 - create_metadata - STEP_INPUT - Got input "images" of type "Any". (Type check passed).
[32m2021-07-22 18:10:03[0m - dagster - [34mDEBUG[0m - metadata_pipeline - 81f73056-151b-40a3-aa30-1ca9bcc9a997 - 5758 - create_metadata - STEP_INPUT - Got input "jstor" of type "Any". (Type check passed).
[32m2021-07-22 18:10:03[0m - dagster - [34mDEBUG[0m - metadata_pipeline - 81f73056-151b-40a3-aa30-1ca9bcc9a997 - 5758 - create_metadata - STEP_INPUT - Got input "portals" of type "Any". (Type check passed).
[32m2021-07-22 18:10:03[0m - dagster - [34mDEBUG[0m - metadata_pipeline - 81f73056-151b-40a3-aa30-1ca9bcc9a997 - 5758 - create_metadata - STEP_INPUT - Got input "wikidata" of type "Any". (Type check passed).
[32m2021-07-22 18:10:03[0m - dagster - [34mERROR[0m - [31mmetadata_pipeline - 81f73056-151b-40a3-aa30-1ca9bcc9a997 - 5758 - create_metadata - STEP_FAILURE - Execution of step "create_metadata" failed.

dagster.core.errors.DagsterExecutionStepExecutionError: Error occurred while executing solid "create_metadata"::

KeyError: "['longitude', 'latitude'] not in index"

Stack Trace:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/dagster/core/execution/plan/utils.py", line 42, in solid_execution_error_boundary
    yield
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/dagster/utils/__init__.py", line 383, in iterate_with_context
    next_output = next(iterator)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/dagster/core/execution/plan/compute_generator.py", line 65, in _coerce_solid_compute_fn_to_iterator
    result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
  File "pipelines/metadata_pipeline.py", line 91, in create_metadata
    "Media URL",  # Media URL do images
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/core/frame.py", line 2912, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/core/indexing.py", line 1254, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/core/indexing.py", line 1304, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
[0m
